### ISSUE TITLE
invalid cast exception

### ISSUE THREAD

**Issue by mdissel** [ticky74/ServiceStack.Authentication.Azure#2] opened 2017-04-11 12:57 UTC
When I try to login (using a form POST to /auth/ms-graph)  this exception is raised:

`[Authenticate: 11-4-2017 12:34:30]:\n[REQUEST: {provider:ms-graph,userName:admin@XXXX.XX}]\nSystem.InvalidCastException: Unable to cast object of type 'Microsoft.AspNetCore.Http.Internal.QueryCollection' to type 'System.Collections.Specialized.NameValueCollection'.\r\n   at ServiceStack.Authentication.Azure.AzureAuthenticationProvider.Authenticate(IServiceBase authService, IAuthSession session, Authenticate request)\r\n   at ServiceStack.Auth.AuthenticateService.Authenticate(Authenticate request, String provider, IAuthSession session, IAuthProvider oAuthConfig) in /opt/lib/teamcity-agent/work/d09206570215629/src/ServiceStack/Auth/AuthenticateService.cs:line 284\r\n   at ServiceStack.Auth.AuthenticateService.Post(Authenticate request) in /opt/lib/teamcity-agent/work/d09206570215629/src/ServiceStack/Auth/AuthenticateService.cs:line 145\r\n   at ServiceStack.Host.ServiceRunner'1.Execute(IRequest request, Object instance, TRequest requestDto) in /opt/lib/teamcity-agent/work/d09206570215629/src/ServiceStack/Host/ServiceRunner.cs:line 107`

**Comment by ticky74** [comment] 2017-04-11 14:23
Thanks Marco, will look at this today.
ian

**Comment by ticky74** [comment] 2017-04-12 01:37
Hey Marco,
I couldn't reproduce the bug on my end. However, there was a line where I was using an extension method that had a cast within it so I have updated the code, hopefully that fixes your issue. Could you let me know one way or the other so I can either close the issue or keep hunting it down.
ian

**Comment by mdissel** [comment] 2017-04-12 07:08
It's working now! Thanks.. maybe report this extension bug in servicestack?

**Comment by ticky74** [comment] 2017-04-12 12:56
Thanks again Marco, I appreciate the report. Hope the library helps out.
ian

**Closed by ticky74** 2017-04-12 12:56 UTC

**Comment by mdissel** [comment] 2017-04-12 13:30
Yes, it really does! Thanks for the efforts!
